// Codigos de error del backend para validacion de ubicaciones
export const LOCATION_ERROR_CODES = {
  INVALID_LOCATION: 'INVALID_LOCATION',
  SELLER_INVALID_TRADE_DEPARTMENT: 'SELLER_INVALID_TRADE_DEPARTMENT',
  SELLER_INVALID_TRADE_CITY: 'SELLER_INVALID_TRADE_CITY',
};

// Codigos de error generales del backend
export const API_ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CUSTOMER_ALREADY_EXISTS: 'CUSTOMER_ALREADY_EXISTS',
  EMPTY_CART: 'EMPTY_CART',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  SELLER_ALREADY_EXISTS: 'SELLER_ALREADY_EXISTS',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ILLEGAL_ARGUMENT: 'ILLEGAL_ARGUMENT',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
